name: bayarku
description: POS in flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.0.0                      # Router
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  flutter_riverpod: ^2.0.0-dev.9        # riverpod as state management tools
  json_serializable: ^6.3.1
  retrofit: ^3.0.1+1
  flutter_launcher_icons: ^0.11.0       # launcher config
  google_fonts: ^3.0.1                  # google font collection
  easy_localization: ^3.0.1             # i18n language
  flutter_svg: ^1.1.6                   # flutter svg vector drawable assets


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  logger: ^1.0.0
  mockito: ^5.3.0                       # Testing fake object
  retrofit_generator: ^4.0.3+1
  build_runner: ^2.0.6
  freezed: ^2.1.0+1  

flutter:
  uses-material-design: true
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Medium.otf
        - asset: fonts/SFProDisplay-Regular.otf
        - asset: fonts/SFProDisplay-Bold.otf
    
    - family: SFProText
      fonts:
        - asset: fonts/SFProText-Regular.ttf
      
  assets:
    - images/